server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ @route;
    }

    location @route {
        rewrite ^/(restaurants/[^/]+|bookmarks|mypage)/?$ /index.html last;
        return 301 /;
    }
}
